#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=10gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission


#Starting in GBS/ProcessRadtags/Indicies
cd ${PBS_O_WORKDIR} || exit

source ~/.bash_profile
module load GNU/4.9
module load GMAP/20160609

gmap_build -d Moghe2014_GS -k 15 /mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/RrContigs.fa.fasta -D .


#Launch mapper
rc=$?

if [[ $rc = 0 ]]

then cd ../../RawFastq/ || exit
     ThisT=`ls *fastq.gz | wc -w`
     ThisT=`expr $ThisT - 1`
     qsub ../supreme-octo-disco/1.1_ProcessRadtags.qsub -N ProcessingRads -t 0-${ThisT}
fi
