#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=64gb
#PBS -m a
#PBS -t 0-200
#PBS -l feature='intel16'

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission




#Starting in GBS/ProcessRadtags/
cd ${PBS_O_WORKDIR} || exit

source ~/.bash_profile
module load GNU/4.9
module load GMAP/20160609
module load SAMTools/1.2


filelist=(*fq) #Get a list of all sequencing files

indiv=${filelist[${PBS_ARRAYID}]} #assign indiv to be current sequence file

bsname=${PBS_ARRAYID}_${indiv}

echo bsname="${bsname}"

if [ ! -f ${indiv}_q20.sam ]
 then gsnap -t 6 -d ${index} -D Indicies/ --force-single-end -i 2 -k 15 \
 --min-coverage=0.95 --terminal-threshold=10 -o ${indiv}.sam -A sam ${indiv}
 samtools view -q 20 -T ${genome} ${indiv}.sam > ${indiv}_q20.sam
fi


if [ ! -f ${indiv}_q20.sam ]
  then qsub ../supreme-octo-disco/1.2_GSMap.qsub -N ${MapFolder} -t ${PBS_ARRAYID}\
  -v genome="${genome}",gff="${gff}",gffi="${gffi}",exon="${exon}",stranded="${stranded}",\
  MAXJOBID="${MAXJOBID}",index="${index}",MapFolder="${MapFolder}"
  echo "I broke during mapping"
fi




if [ -f ${indiv}_q20.sam ]
  then echo ${bsname} >> FilesMapped.txt
fi

runs=$(cat FilesMapped.txt | wc -l)
# Calculate next job to run
NEXT=$(( ${PBS_ARRAYID} + 200 ))


#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    echo "I want to run job" ${NEXT}
    qsub ../supreme-octo-disco/1.2_GSMap.qsub -N ${MapFolder} -t ${NEXT} -v genome="${genome}",gff="${gff}",gffi="${gffi}",exon="${exon}",stranded="${stranded}",MAXJOBID="${MAXJOBID}",index="${index}",MapFolder="${MapFolder}"
    echo "I started the next job"
fi

#Launch first step of STACKS if all the mapping is done


if [ ${runs} = ${MAXJOBID} ]
then bash ../supreme-octo-disco/2_Submit_P_STACKS.sh
fi

#Then launch metadata collector, once per reference per dataset

if [ ${PBS_ARRAYID} = 0 ]
  then cd ${PBS_O_WORKDIR} || exit
  echo "I'm gonna metadata"
  qsub ../supreme-octo-disco/1.3_echo.qsub -N ${MapFolder}.metadata\
  -v genome="${genome}",index="${index}",gff="${gff}",bsname="${bsname}",\
  gffi="${gffi}",exon="${exon}"
fi
