#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=64gb
#PBS -m a
#PBS -t 0-200

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission




#Starting in GBS/ProcessRadtags/
cd ${PBS_O_WORKDIR} || exit

source ~/.bash_profile

module load SAMTools/1.2


filelist=(*fq) #Get a list of all sequencing files

indiv=${filelist[${PBS_ARRAYID}]} #assign indiv to be current sequence file

bsname=${PBS_ARRAYID}_${indiv}


cd ${MapFolder}/ || exit

echo bsname="${bsname}"

if [[ ! -f ${indiv}_q20.sam ]]
 then gsnap -t 6 -d ${index} --force-single-end -m 5 -i 2 -k 15 \
 --min-coverage=0.95 -o ${indiv}.sam -A sam ../${indiv}
 samtools view -q 20 -T ${genome} ${indiv}.sam > ${indiv}_q20.sam
 echo ${bsname} >> FilesMapped.txt
fi


if [[ ! -f ${indiv}_q20.sam ]]
then qsub ../../supreme-octo-disco/1.2_GSMap.qsub -N ${MapFolder} -t ${PBS_ARRAYID}\
-v genome="${genome}",gff="${gff}",gffi="${gffi}",exon="${exon}",stranded="${stranded}",\
MAXJOBID="${MAXJOBID}",index="${index}",MapFolder="${MapFolder}"
fi

if [[ -f ${indiv}_q20.sam ]]
then runs=$(cat FilesMapped.txt | wc -l)
fi

# Calculate next job to run
NEXT=$(( ${PBS_ARRAYID} + 200 ))


#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR} || exit
    qsub ../../supreme-octo-disco/1.2_GSMap.qsub -N ${MapFolder} -t ${PBS_ARRAYID}\
    -v genome="${genome}",gff="${gff}",gffi="${gffi}",exon="${exon}",stranded="${stranded}",\
    MAXJOBID="${MAXJOBID}",index="${index}",MapFolder="${MapFolder}"
    cd - || exit
fi

#Launch first step of STACKS if all the mapping is done


if [ ${runs} = 1440 ]
then bash ../../supreme-octo-disco/2_Submit_P_STACKS.sh
fi

#Then launch metadata collector, once per reference per dataset

if [[ ${PBS_ARRAYID} = 0 ]]
then cd ${PBS_O_WORKDIR} || exit
qsub ../supreme-octo-disco/1.3_echo.qsub -N ${MapFolder}.metadata\
-v genome="${genome}",index="${index}",gff="${gff}",bsname="${bsname}",\
gffi="${gffi}",exon="${exon}"
fi
