#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=04:00:00,mem=10gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission


module load SAMTools/1.2

#Starting in the BT2Map folder
cd ${PBS_O_WORKDIR} || exit



# Filters out any mapping qualities less than 30
echo ${bsname}

samtools view -q 30 -b -T ${genome} ${job}.sam > ${job}.bam


samtools sort ${job}.bam ${job}.sorted

samtools index ${job}.sorted.bam

### Send alignment to stacks


ThisT=`ls ../*.fq | wc -w`

BAMdone=`ls *.sorted.bam | wc -l`

if [ ${BAMdone} = ${ThisT}]
then ../../supreme-octo-disco/1.4_ChooseSigSel.sh
cd SigSelection
qsub ../../../supreme-octo-disco/1.5_Pop_STACKS.qsub -N ${bsname}.popSTACKS -v genome="${genome}",index="${index}",gff="${gff}",bsname="${bsname}",job="${job}",gffi="${gffi}",exon="${exon}",stranded="${stranded}"
cd ../AE_Deconvoluted
qsub ../../../supreme-octo-disco/1.5_GenMap_STACKS.qsub -N ${bsname}.mapSTACKS -v genome="${genome}",index="${index}",gff="${gff}",bsname="${bsname}",job="${job}",gffi="${gffi}",exon="${exon}",stranded="${stranded}"
qsub ../../../supreme-octo-disco/1.5_Pop_STACKS.qsub -N ${bsname}.popSTACKS -v genome="${genome}",index="${index}",gff="${gff}",bsname="${bsname}",job="${job}",gffi="${gffi}",exon="${exon}",stranded="${stranded}"
fi

