#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=10gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

#Starting in AE_Deconvoluted
cd ${PBS_O_WORKDIR} || exit


module load stacks/1.35

dt=`date '+%d_%m_%Y'`

# Run Stacks on the BT2 data

ref_map.pl -S -m 3 -T 8 -b ${dt} -o GenMapSTACKS/ -A F2 -X "genotypes:-o 'rqtl'" -X "genotypes:-o 'genomic'" -X "genotypes:-e 'pstI'"\
-r ./*13253*.sorted.bam \
-r ./*13254*.sorted.bam \
-r ./*13255*.sorted.bam \
-r ./*13256*.sorted.bam \
-r ./*13257*.sorted.bam \
-r ./*13258*.sorted.bam \
-r ./*13259*.sorted.bam \
-r ./*13260*.sorted.bam \
-r ./*13261*.sorted.bam \
-r ./*13262*.sorted.bam \
-r ./*13263*.sorted.bam \
-r ./*13264*.sorted.bam \
-r ./*13265*.sorted.bam \
-r ./*13266*.sorted.bam \
-r ./*13267*.sorted.bam \
-r ./*13268*.sorted.bam \
-r ./*13269*.sorted.bam \
-r ./*13270*.sorted.bam \
-r ./*13271*.sorted.bam \
-r ./*13272*.sorted.bam \
-r ./*13273*.sorted.bam \
-r ./*13274*.sorted.bam \
-r ./*13275*.sorted.bam \
-r ./*13276*.sorted.bam \
-r ./*13277*.sorted.bam \
-r ./*13278*.sorted.bam \
-r ./*13279*.sorted.bam \
-r ./*13280*.sorted.bam \
-r ./*13281*.sorted.bam \
-r ./*13282*.sorted.bam \
-r ./*13283*.sorted.bam \
-r ./*13284*.sorted.bam \
-r ./*13285*.sorted.bam \
-r ./*13286*.sorted.bam \
-r ./*13287*.sorted.bam \
-r ./*13288*.sorted.bam \
-r ./*13289*.sorted.bam \
-r ./*13290*.sorted.bam \
-r ./*13291*.sorted.bam \
-r ./*13292*.sorted.bam \
-p ./*13210*.sorted.bam \
-p ./*13211*.sorted.bam \
-p ./*13212*.sorted.bam \
-p ./*13213*.sorted.bam \
-p ./*13214*.sorted.bam \
-p ./*13215*.sorted.bam \
-p ./*13216*.sorted.bam \
-p ./*13217*.sorted.bam \
-p ./*13218*.sorted.bam \
-p ./*13219*.sorted.bam \
-p ./*13220*.sorted.bam \
-p ./*13221*.sorted.bam \
-p ./*13222*.sorted.bam \
-p ./*13223*.sorted.bam \
-p ./*13224*.sorted.bam \
-p ./*13225*.sorted.bam \
-p ./*13226*.sorted.bam \
-p ./*13227*.sorted.bam \
-p ./*13228*.sorted.bam \
-p ./*13229*.sorted.bam \
-p ./*13230*.sorted.bam \
-p ./*13231*.sorted.bam \
-p ./*13232*.sorted.bam \
-p ./*13233*.sorted.bam \
-p ./*13234*.sorted.bam \
-p ./*13235*.sorted.bam \
-p ./*13236*.sorted.bam \
-p ./*13237*.sorted.bam \
-p ./*13238*.sorted.bam \
-p ./*13239*.sorted.bam \
-p ./*13240*.sorted.bam \
-p ./*13241*.sorted.bam \
-p ./*13242*.sorted.bam \
-p ./*13243*.sorted.bam \
-p ./*13244*.sorted.bam \
-p ./*13245*.sorted.bam \
-p ./*13246*.sorted.bam \
-p ./*13247*.sorted.bam \
-p ./*13248*.sorted.bam \
-p ./*13249*.sorted.bam \
-p ./*13250*.sorted.bam \
-p ./*13251*.sorted.bam \
-p ./*13252*.sorted.bam 
