#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=48:00:00,mem=10gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

#Starting in AE_Deconvoluted

cd ${PBS_O_WORKDIR} || exit

module load stacks/1.35

rc=`pwd`
rc=`basename $rc`

dt=`date '+%Y%m%d'`

# Run Stacks on the BT2 data

#All F2s from AE plants, no parents, no F1s

ref_map.pl -S -m 3 -T 8 -b ${dt} -o PopSTACKS/ -A F2 \ #-X "populations:--fstats" \
-X "populations:--treemix" -X "populations:--structure" -X "populations:--vcf" \
-X "populations:--renz 'pstI'" -X "populations:--write_single_snp" -X "populations:--genomic" \
-O ../../../Metadata/${rc}.pop \
-s 13210_QTL_F2_11.fq.sam \
-s 13210_QTL_F2_12.fq.sam \
-s 13211_QTL_F2_11.fq.sam \
-s 13211_QTL_F2_12.fq.sam \
-s 13212_QTL_F2_11.fq.sam \
-s 13212_QTL_F2_12.fq.sam \
-s 13213_QTL_F2_11.fq.sam \
-s 13213_QTL_F2_12.fq.sam \
-s 13214_QTL_F2_11.fq.sam \
-s 13214_QTL_F2_12.fq.sam \
-s 13215_QTL_F2_11.fq.sam \
-s 13215_QTL_F2_12.fq.sam \
-s 13216_QTL_F2_11.fq.sam \
-s 13216_QTL_F2_12.fq.sam \
-s 13217_QTL_F2_11.fq.sam \
-s 13217_QTL_F2_12.fq.sam \
-s 13218_QTL_F2_11.fq.sam \
-s 13218_QTL_F2_12.fq.sam \
-s 13219_QTL_F2_11.fq.sam \
-s 13219_QTL_F2_12.fq.sam \
-s 13220_QTL_F2_11.fq.sam \
-s 13220_QTL_F2_12.fq.sam \
-s 13221_QTL_F2_11.fq.sam \
-s 13221_QTL_F2_12.fq.sam \
-s 13222_QTL_F2_11.fq.sam \
-s 13222_QTL_F2_12.fq.sam \
-s 13223_QTL_F2_11.fq.sam \
-s 13223_QTL_F2_12.fq.sam \
-s 13224_QTL_F2_11.fq.sam \
-s 13224_QTL_F2_12.fq.sam \
-s 13225_QTL_F2_11.fq.sam \
-s 13225_QTL_F2_12.fq.sam \
-s 13226_QTL_F2_11.fq.sam \
-s 13226_QTL_F2_12.fq.sam \
-s 13227_QTL_F2_11.fq.sam \
-s 13227_QTL_F2_12.fq.sam \
-s 13228_QTL_F2_11.fq.sam \
-s 13228_QTL_F2_12.fq.sam \
-s 13229_QTL_F2_11.fq.sam \
-s 13229_QTL_F2_12.fq.sam \
-s 13230_QTL_F2_11.fq.sam \
-s 13230_QTL_F2_12.fq.sam \
-s 13231_QTL_F2_11.fq.sam \
-s 13231_QTL_F2_12.fq.sam \
-s 13232_QTL_F2_11.fq.sam \
-s 13232_QTL_F2_12.fq.sam \
-s 13233_QTL_F2_11.fq.sam \
-s 13233_QTL_F2_12.fq.sam \
-s 13234_QTL_F2_11.fq.sam \
-s 13234_QTL_F2_12.fq.sam \
-s 13235_QTL_F2_11.fq.sam \
-s 13235_QTL_F2_12.fq.sam \
-s 13236_QTL_F2_11.fq.sam \
-s 13236_QTL_F2_12.fq.sam \
-s 13237_QTL_F2_11.fq.sam \
-s 13237_QTL_F2_12.fq.sam \
-s 13238_QTL_F2_11.fq.sam \
-s 13238_QTL_F2_12.fq.sam \
-s 13239_QTL_F2_11.fq.sam \
-s 13239_QTL_F2_12.fq.sam \
-s 13240_QTL_F2_11.fq.sam \
-s 13240_QTL_F2_12.fq.sam \
-s 13241_QTL_F2_11.fq.sam \
-s 13241_QTL_F2_12.fq.sam \
-s 13242_QTL_F2_11.fq.sam \
-s 13242_QTL_F2_12.fq.sam \
-s 13243_QTL_F2_11.fq.sam \
-s 13243_QTL_F2_12.fq.sam \
-s 13244_QTL_F2_11.fq.sam \
-s 13244_QTL_F2_12.fq.sam \
-s 13245_QTL_F2_11.fq.sam \
-s 13246_QTL_F2_11.fq.sam \
-s 13246_QTL_F2_12.fq.sam \
-s 13247_QTL_F2_11.fq.sam \
-s 13247_QTL_F2_12.fq.sam \
-s 13248_QTL_F2_11.fq.sam \
-s 13248_QTL_F2_12.fq.sam \
-s 13249_QTL_F2_11.fq.sam \
-s 13249_QTL_F2_12.fq.sam \
-s 13250_QTL_F2_11.fq.sam \
-s 13250_QTL_F2_12.fq.sam \
-s 13251_QTL_F2_12.fq.sam \
-s 13251_QTL_F2_1.fq.sam \
-s 13252_QTL_F2_12.fq.sam \
-s 13252_QTL_F2_1.fq.sam