#!/bin/bash -login
 
### define resources needed:
### walltime - how long you expect the job to run
#PBS -l walltime=04:00:00
  
### nodes:ppn - how many nodes & cores per node (ppn) that you require
#PBS -l nodes=1:ppn=1
#PBS -l feature=gbe    
### mem: amount of memory that the job will need
#PBS -l mem=2gb
##PBS -m abe     
### you can give your job a name for easier identification

cd ${PBS_O_WORKDIR}

module load FastQC/0.11.3

fastqc -v > ../versions.txt

fastqc -o . ../../RawFastq/*.fastq


cd ../../RawFastq

qsub ../../supreme-octo-disco/3_ProcessRadtags.qsub