#!/bin/bash -login
 
### define resources needed:
### walltime - how long you expect the job to run
#PBS -l walltime=04:00:00
  
### nodes:ppn - how many nodes & cores per node (ppn) that you require
#PBS -l nodes=1:ppn=1
#PBS -l feature=gbe    
### mem: amount of memory that the job will need
#PBS -l mem=2gb
##PBS -m abe
#PBS -t 0-14
### you can give your job a name for easier identification


module load stacks/1.35

#Starting in GBS/RawFastq/
cd ${PBS_O_WORKDIR}

filelist=(*.fastq) #get list of sequencing lanes

lane=${filelist[${PBS_ARRAYID}]} #assign indiv to be current sequence file

barcode=`basename ${lane} .fastq`.barcodes

PBS_JOBNAME=${PBS_JOBNAME}_${lane} #rename job to job_indiv

process_radtags -f ${lane} -i fastq -o ../ProcessRadtags/ -b ../Metadata/PlateInfoSeq/${barcode} -c -q -D -e 'pstI' --adapter_1 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT' --adapter_mm 3 --retain_header

cd ../fastQC/TrimmedFQC

qsub ../../supreme-octo-disco/4_FastQC_trimmed.qsub