#!/bin/bash -login
 
### define resources needed:
### walltime - how long you expect the job to run
#PBS -l walltime=04:00:00
  
### nodes:ppn - how many nodes & cores per node (ppn) that you require
#PBS -l nodes=1:ppn=1
#PBS -l feature=gbe    
### mem: amount of memory that the job will need
#PBS -l mem=2gb
##PBS -m abe     
### you can give your job a name for easier identification

#Starting in GBS/fastQC/TrimmedFQC/
cd ${PBS_O_WORKDIR}

source ~/.bash_profile
module load FastQC/0.11.3
module load bowtie2/2.2.6

#Run FastQC again

fastqc -o . ../../ProcessRadtags/*.fq

cd ../../ProcessRadtags/

sh ../supreme-octo-disco/ChooseSigSel.sh

cd Indicies/

#Build indicies for mapping

bowtie2-build /mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/RrContigs.fa.fasta Moghe2014_BT 


#Start Mapper

cd ../SigSelection/BT2map/

qsub ../../supreme-octo-disco/5_BT2Map.qsub -v genome=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/RrContigs.fa.fasta,gff=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/Rr_gene_pseu.gff.mod,gffi="Parent",exon="exon",stranded="no"


cd ../../AE_Deconvoluted/BT2map/

qsub ../../supreme-octo-disco/5_BT2Map.qsub -v genome=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/RrContigs.fa.fasta,gff=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/Rr_gene_pseu.gff.mod,gffi="Parent",exon="exon",stranded="no"

