#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=04:00:00,mem=10gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

#Starting in one of the BT2Map folders
cd ${PBS_O_WORKDIR} || exit

module load stacks/1.35

cd ..
rc=`pwd`
rc=`basename $rc`

cd ${PBS_O_WORKDIR}


filelist=(*fq) #Get a list of all sequencing files

indiv=${filelist[${PBS_ARRAYID}]} #assign indiv to be current sequence file

PBS_JOBNAME=${PBS_JOBNAME}_${indiv} #rename job to job_indiv



dt=`date '+%d_%m_%Y'`

# Run Stacks on the BT2 data

ref_map.pl -S -m 3 -T 8 -b ${dt} -o ../PopSTACKS/ -A F2 -X "populations:--fstats" \
-X "populations:--treemix" -X "populations:--structure" -X "populations:--vcf" \
-X "populations:--renz 'pstI'" -X "populations:--write_single_snp" -X "populations:--genomic" \
--samples ./ -O ../../supreme-octo-disco/${rc}.pop