#!/bin/bash -login
 
### define resources needed:
### walltime - how long you expect the job to run
#PBS -l walltime=04:00:00
  
### nodes:ppn - how many nodes & cores per node (ppn) that you require
#PBS -l nodes=1:ppn=1
#PBS -l feature=gbe    
### mem: amount of memory that the job will need
#PBS -l mem=2gb
##PBS -m abe 
#PBS -t 1-400    
### you can give your job a name for easier identification

#Starting in GBS/ProcessRadtags/
cd ${PBS_O_WORKDIR}

source ~/.bash_profile
module load FastQC/0.11.3
module load bowtie2/2.2.6

#Run FastQC again

ThisT=`ls *.fq | wc -w`

filelist=(*.fq) #get list of sequencing lanes

fastqfile=${filelist[${PBS_ARRAYID}]} #assign indiv to be current sequence file

fastqc -o ../fastQC/TrimmedFQC/ ${fastqfile}

fqcT=`ls ../fastQC/TrimmedFQC/*fastqc.zip | wc -w`


# Calculate next job to run
NEXT=$(( ${PBS_ARRAYID} + 400 ))
JOBSCRIPT=../supreme-octo-disco/FastQC_trimmed.qsub

#Check to see if next job is past the maximum job id
if [ ${NEXT} -le ${MAXJOBID} ]
then
    cd ${PBS_O_WORKDIR}
    qsub -t ${NEXT} ${JOBSCRIPT} -v MAXJOBID=${MAXJOBID}
fi


#Start Mapper
if [ ${ThisT} = ${fqcT} ]

then sh ../supreme-octo-disco/ChooseSigSel.sh

cd SigSelection/

ThisT=`ls *.fq | wc -w`

ThisT=`expr ${ThisT} - 1`

qsub ../../supreme-octo-disco/BT2Map.qsub -v genome=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/RrContigs.fa.fasta,gff=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/Rr_gene_pseu.gff.mod,gffi="Parent",exon="exon",stranded="no",MAXJOBID=${ThisT}
cd ../AE_Deconvoluted/

ThisT=`ls *.fq | wc -w` 

ThisT=`expr ${ThisT} - 1`

qsub ../../supreme-octo-disco/BT2Map.qsub -v genome=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/RrContigs.fa.fasta,gff=/mnt/research/radishGenomics/AnalysisOfSequencingFiles/MoghePublished/Rr_gene_pseu.gff.mod,gffi="Parent",exon="exon",stranded="no",MAXJOBID=${ThisT}

fi