---
title: "FstOutlier"
author: "Amanda Charbonneau"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    collapsed: no
    df_print: paged
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_notebook:
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Install function for packages    
packages<-function(x){
  x<-as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}
packages(dplyr)
packages(tidyr)
packages(RColorBrewer)
packages(ggplot2)
packages(knitr)
source("../supreme-octo-disco/R functions/plot_R.r")

```


```{r PairwiseFST}

pdf(file="../figures/PairwiseFstAll.pdf")

ALLTHEFILES <- dir("../ProcessRadtags/SS_20180420_P_Pop20_Ind.80_m2_n7/", pattern = ".*fst_.*-.*")


File_Num <- length(ALLTHEFILES)

File_list <- data.frame(matrix(unlist(strsplit(ALLTHEFILES, "\\_|\\-|\\.")), ncol = 6, byrow = T))
File_list$runname <- ALLTHEFILES
colnames(File_list) <- c("batch", "Date", "fst", "Pop1", "Pop2", "tsv", "runname")
File_list <- select(File_list, runname, Date, Pop1, Pop2)

Outliers <- data.frame()

for( fst_file in c(1:length(File_list$runname))){
  #fst_file <- 2
  dataset <- File_list[fst_file, 1]
  fst_comp <- 0
  fst_comp <- read.csv(paste("../ProcessRadtags/SS_20180420_P_Pop20_Ind.80_m2_n7/", 
                             dataset, sep=""), sep = "\t")
  fst_comp$BHfisherP <- p.adjust(fst_comp$Fisher.s.P, method = "BH")
  fst_comp$sigBHFisherP <- fst_comp$BHfisherP < .05
  fst_comp$row <- 1:length(fst_comp$X..Batch.ID)
  sigrows <- filter(fst_comp, sigBHFisherP == TRUE)
  Outliers <- rbind(Outliers, sigrows)
  print(ggplot(fst_comp, aes(row, Smoothed.Fst, col= LOD, shape=sigBHFisherP )) + 
          geom_point() + scale_colour_gradientn(colours= c("Black", "Red")) + 
    ggtitle(paste("Fst ", File_list$Pop1[fst_file], " vs ", File_list$Pop2[fst_file], sep="")))

  print(ggplot(fst_comp, aes(row, Overall.Pi)) + 
          geom_point() + 
    ggtitle(paste("Fst ", File_list$Pop1[fst_file], " vs ", File_list$Pop2[fst_file], sep="")))
   
  print(ggplot(fst_comp, aes(Overall.Pi, Smoothed.Fst, col= LOD, shape=sigBHFisherP  )) + 
          geom_point() + scale_colour_gradientn(colours= c("Black", "Red")) + 
    ggtitle(paste("Fst ", File_list$Pop1[fst_file], " vs ", File_list$Pop2[fst_file], sep="")))

}

dev.off()
head(Outliers)
write.csv(Outliers, "../ProcessRadtags/JustRRRs/StacksOutliers.csv", col.names = T )
```

```{r}

pdf(file="../figures/BayesFst.pdf")

ALLTHEFILES <- dir("../ProcessRadtags/JustRRRs/BayeScan/", pattern = ".*_fst.txt")

hits <- list()

File_Num <- length(ALLTHEFILES)

for (i in 1:length(ALLTHEFILES)) {
  results <- plot_bayescan(paste("../ProcessRadtags/JustRRRs/BayeScan/", ALLTHEFILES[i], sep = ""),
                FDR = .05, add_text = T)
  title(ALLTHEFILES[i])
  hits <- c(hits, results$outliers)

}

dev.off()

hits
```

```{r}

pdf(file="../figures/BayesFst_05.pdf")

ALLTHEFILES <- dir("../ProcessRadtags/JustRRRs/BayeScan_05/", pattern = ".*_fst.txt")

File_Num <- length(ALLTHEFILES)

hits_05 <- list()

for (i in 1:length(ALLTHEFILES)) {
  results <- plot_bayescan(paste("../ProcessRadtags/JustRRRs/BayeScan_05/", ALLTHEFILES[i], 
                sep = ""), FDR = .05, add_text = T)
  title(ALLTHEFILES[i])
  hits_05 <- c(hits_05, results$outliers)
}

dev.off()

hits_05

```
