#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=8,walltime=8:00:00,mem=64gb
#PBS -m a

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

#Starting in SigSelection

cd ${PBS_O_WORKDIR} || exit

module load stacks/1.35

rc=`pwd`
rc=`basename $rc`

dt=`date '+%Y%m%d'`


populations -b 20170214 -P PopSTACKS -s -t 8 --treemix --structure --vcf --renz 'pstI' --write_random_snp --verbose -p 16 -r 0.75 --ordered_export -M ../../../Metadata/${rc}.pop